'use client';
import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { useCart } from '@/components/CartContext';

export default function CartPage() {
  const { items, removeItem, updateQty, total } = useCart();
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const checkout = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/checkout', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ items }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Checkout failed'); window.location.href = data.url; } catch(e) { setError(e.message); setLoading(false); } };
  if (!items.length) return (<><Header /><main className="max-w-3xl mx-auto px-4 py-24 text-center"><div className="text-6xl mb-4">🛒</div><h1 className="text-3xl font-black mb-4">Your Cart is Empty</h1><p className="text-gray-500 mb-8">Design your custom car tray to get started.</p><Link href="/customize" className="inline-flex items-center px-8 py-4 bg-orange-500 hover:bg-orange-600 text-white font-bold rounded-xl transition-colors">🎨 Start Designing</Link></main><Footer /></>);
  return (<><Header /><main className="max-w-5xl mx-auto px-4 py-10"><h1 className="text-3xl font-black mb-8">Your Cart</h1><div className="grid lg:grid-cols-3 gap-8"><div className="lg:col-span-2 space-y-4">{items.map(item => (<div key={item.cartId} className="flex gap-4 p-4 bg-white border border-gray-100 rounded-2xl shadow-sm">{item.previewUrl && <div className="w-28 h-20 relative rounded-xl overflow-hidden flex-shrink-0 bg-gray-100"><Image src={item.previewUrl} alt="Design" fill className="object-cover" /></div>}<div className="flex-1 min-w-0"><h3 className="font-bold">{item.productName}</h3><p className="text-xs text-gray-400 font-mono">Design #{item.designId?.slice(-8)}</p><p className="text-sm text-gray-500 mt-1">${(item.price/100).toFixed(2)} each</p><div className="flex items-center gap-3 mt-3"><div className="flex items-center border border-gray-200 rounded-lg overflow-hidden"><button onClick={() => updateQty(item.cartId, item.quantity-1)} className="px-3 py-1.5 text-gray-500 hover:bg-gray-100 font-bold text-sm">−</button><span className="px-3 py-1.5 text-sm font-semibold border-x border-gray-200">{item.quantity}</span><button onClick={() => updateQty(item.cartId, item.quantity+1)} className="px-3 py-1.5 text-gray-500 hover:bg-gray-100 font-bold text-sm">+</button></div><button onClick={() => removeItem(item.cartId)} className="text-xs text-red-400 hover:text-red-600 transition-colors">Remove</button></div></div><div className="font-bold text-lg text-right flex-shrink-0">${((item.price*item.quantity)/100).toFixed(2)}</div></div>))}<Link href="/customize" className="inline-flex items-center text-sm text-orange-500 hover:underline font-semibold mt-2">+ Add Another Design</Link></div><div><div className="bg-gray-50 rounded-2xl p-6 sticky top-20"><h2 className="font-bold text-lg mb-4">Order Summary</h2><div className="space-y-2 mb-4 text-sm">{items.map(i => <div key={i.cartId} className="flex justify-between text-gray-600"><span>{i.productName} ×{i.quantity}</span><span>${((i.price*i.quantity)/100).toFixed(2)}</span></div>)}<div className="border-t border-gray-200 pt-2 mt-2 flex justify-between font-black text-lg"><span>Total</span><span>${(total/100).toFixed(2)}</span></div></div><p className="text-xs text-gray-500 mb-4">Shipping details shown at checkout</p>{error && <p className="text-sm text-red-500 mb-3 bg-red-50 border border-red-100 rounded-lg px-3 py-2">⚠ {error}</p>}<button onClick={checkout} disabled={loading} className="w-full py-4 bg-orange-500 hover:bg-orange-600 disabled:bg-gray-300 text-white font-black text-lg rounded-xl transition-colors">{loading ? 'Redirecting...' : '💳 Proceed to Checkout'}</button><div className="flex items-center justify-center gap-2 mt-3 text-xs text-gray-400">🔒 Secured by Stripe</div></div></div></div></main><Footer /></>);
}
