import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
export default function HomePage() {
  const steps=[['01','🎨','Design It','Upload a photo or let AI create artwork you can customize.'],['02','👁️','Preview It','Adjust, zoom and rotate your artwork before ordering.'],['03','💳','Order It','Use secure checkout. Your production file is saved automatically.'],['04','📦','We Make It','Your approved design moves into production after your order is confirmed.']];
  const specs=[['🔷','Material','Cast acrylic — crystal clear, 3/8 in (9 mm)'],['📏','Thickness','3/8 in (9 mm)'],['📐','Design Area','16.5 in wide × 7.625 in tall'],['🎨','Personalization','Full-color custom artwork']];
  return (<><Header />
    <section className="relative bg-gradient-to-br from-gray-950 via-gray-900 to-gray-800 text-white min-h-[88vh] flex items-center overflow-hidden"><div className="absolute top-1/4 right-1/4 w-96 h-96 bg-orange-500/10 rounded-full blur-3xl"/><div className="relative z-10 max-w-6xl mx-auto px-4 py-20 grid lg:grid-cols-2 gap-12 items-center"><div><div className="inline-flex items-center gap-2 bg-orange-500/15 text-orange-400 text-sm font-semibold px-4 py-1.5 rounded-full border border-orange-500/20 mb-6">Made to order · Personalized for you</div><h1 className="text-5xl md:text-6xl xl:text-7xl font-black leading-[1.05] mb-6 tracking-tight">Your Car.<br/><span className="text-orange-400">Your Design.</span></h1><p className="text-xl text-gray-300 leading-relaxed mb-8 max-w-lg">A personalized steering-wheel tray for eating, working and life on the road.</p><div className="flex flex-col sm:flex-row gap-4"><Link href="/customize" className="inline-flex items-center justify-center px-8 py-4 bg-orange-500 hover:bg-orange-600 text-white text-lg font-black rounded-2xl">🎨 Customize Your Tray</Link><Link href="/product" className="inline-flex items-center justify-center px-8 py-4 border-2 border-white/20 text-white text-lg font-semibold rounded-2xl">See Product Details</Link></div><p className="mt-5 text-gray-500 text-sm">Premium acrylic · 3/8 in thick · 100% custom</p></div><div className="hidden lg:flex items-center justify-center"><div className="w-80 h-80 rounded-3xl bg-gradient-to-br from-orange-500/20 to-purple-600/20 border border-white/10 flex items-center justify-center"><div className="text-center"><div className="text-8xl mb-4">🚗</div><p className="font-bold text-lg">Your Design Here</p><p className="text-gray-400 text-sm mt-1">Personalized car tray</p><p className="text-orange-400 font-black text-3xl mt-6">$50</p></div></div></div></div></section>
    <section className="py-20 bg-white"><div className="max-w-5xl mx-auto px-4"><div className="text-center mb-14"><div className="text-orange-500 font-bold text-sm uppercase tracking-widest mb-2">Simple Process</div><h2 className="text-3xl md:text-4xl font-black">How It Works</h2></div><div className="grid md:grid-cols-4 gap-6">{steps.map(([n,e,t,d])=><div key={n} className="text-center p-6 rounded-2xl border border-gray-100"><div className="text-3xl mb-3">{e}</div><div className="text-orange-500 font-black text-xs">STEP {n}</div><h3 className="font-black text-lg mb-2">{t}</h3><p className="text-gray-500 text-sm">{d}</p></div>)}</div><div className="text-center mt-10"><Link href="/customize" className="inline-flex px-8 py-4 bg-orange-500 text-white font-black text-lg rounded-2xl">Start Designing →</Link></div></div></section>
    <section className="py-20 bg-gray-50"><div className="max-w-5xl mx-auto px-4 grid md:grid-cols-2 gap-12 items-center"><div><div className="text-orange-500 font-bold text-sm uppercase tracking-widest mb-2">The Product</div><h2 className="text-3xl md:text-4xl font-black mb-6">Premium Acrylic Construction</h2><ul className="space-y-5">{specs.map(([i,l,v])=><li key={l} className="flex gap-3"><span>{i}</span><div><b>{l}: </b><span className="text-gray-600">{v}</span></div></li>)}</ul></div><div className="bg-white rounded-3xl p-12 text-center border border-orange-100"><div className="text-7xl mb-5">🚗</div><div className="text-3xl font-black mb-2">$50</div><p className="text-gray-500 text-sm mb-6">Shipping details shown at checkout</p><Link href="/customize" className="inline-flex px-6 py-3 bg-orange-500 text-white font-bold rounded-xl">Design Yours Now →</Link></div></div></section>
    <section className="py-20 bg-gray-900 text-white"><div className="max-w-4xl mx-auto px-4 text-center"><div className="text-6xl mb-4">✨</div><div className="text-orange-400 font-bold text-sm uppercase tracking-widest mb-2">AI Design Studio</div><h2 className="text-3xl md:text-4xl font-black mb-5">Create It Your Way</h2><p className="text-gray-400 text-lg mb-8">Generate artwork with AI, upload your own image, or use an image URL. Then position and preview it in the Studio.</p><Link href="/customize" className="inline-flex px-8 py-4 bg-orange-500 text-white font-black text-lg rounded-2xl">Open the Design Studio →</Link></div></section>
    <section className="py-20 bg-white"><div className="max-w-3xl mx-auto px-4"><h2 className="text-3xl font-black text-center mb-10">Common Questions</h2><div className="space-y-3">{[['Will it fit my steering wheel?','Fit depends on steering-wheel dimensions and shape. Check the product measurements before ordering.'],['Can I upload my own image?','Yes. The Studio supports your own artwork and photos.'],['What if I do not have artwork?','Use the built-in AI generator and customize the result in the Studio.'],['Where do you ship?','Available destinations and shipping details are shown during checkout.']].map(([q,a])=><details key={q} className="border border-gray-100 rounded-2xl"><summary className="px-6 py-4 font-semibold cursor-pointer">{q}</summary><p className="px-6 pb-5 text-gray-600">{a}</p></details>)}</div></div></section>
    <section className="py-24 bg-orange-500 text-white text-center"><div className="max-w-3xl mx-auto px-4"><h2 className="text-4xl md:text-5xl font-black mb-4">Ready to Design Yours?</h2><p className="text-orange-100 text-xl mb-10">Create your design, preview your tray and place your order securely.</p><Link href="/customize" className="inline-flex px-10 py-5 bg-white text-orange-600 text-xl font-black rounded-2xl">🎨 Customize Your Tray — $50</Link></div></section><Footer /></>);
}
